insert into courses (course_name, course_code, department) values ('Marketing', 'CMA384', 7);
insert into courses (course_name, course_code, department) values ('Legal', 'WXG330', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'QFG741', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'AGQ732', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'TAT471', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'VCO711', 6);
insert into courses (course_name, course_code, department) values ('Services', 'DMV685', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'AWX957', 3);
insert into courses (course_name, course_code, department) values ('Support', 'KPI461', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'XFT216', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'PBV077', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'FJD120', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'XBF189', 2);
insert into courses (course_name, course_code, department) values ('Support', 'GUE026', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'ZIQ132', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'GNH581', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'NFX074', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'XRI154', 5);
insert into courses (course_name, course_code, department) values ('Training', 'NVW183', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'QPS133', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'HOW679', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'QXR113', 6);
insert into courses (course_name, course_code, department) values ('Sales', 'XPW806', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'PSA321', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'DVJ724', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'DTI889', 5);
insert into courses (course_name, course_code, department) values ('Legal', 'QGI049', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'UQU053', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'MLE433', 3);
insert into courses (course_name, course_code, department) values ('Product Management', 'JEC815', 5);
insert into courses (course_name, course_code, department) values ('Support', 'HBF792', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'XSC889', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'YNM708', 3);
insert into courses (course_name, course_code, department) values ('Product Management', 'MMJ302', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'XDV095', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'JHH335', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'LOC086', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'SSH005', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'NPO727', 5);
insert into courses (course_name, course_code, department) values ('Business Development', 'XZZ609', 5);
insert into courses (course_name, course_code, department) values ('Training', 'UUS202', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'AAS997', 5);
insert into courses (course_name, course_code, department) values ('Business Development', 'CXS859', 1);
insert into courses (course_name, course_code, department) values ('Support', 'RKW854', 6);
insert into courses (course_name, course_code, department) values ('Services', 'BHG484', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'CTT143', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'XSW864', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'VLR662', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'ZYO332', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'CQX082', 2);
insert into courses (course_name, course_code, department) values ('Support', 'HWT244', 2);
insert into courses (course_name, course_code, department) values ('Business Development', 'VWN619', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'QMN076', 5);
insert into courses (course_name, course_code, department) values ('Business Development', 'GJJ696', 2);
insert into courses (course_name, course_code, department) values ('Training', 'WLZ363', 6);
insert into courses (course_name, course_code, department) values ('Sales', 'XVN973', 5);
insert into courses (course_name, course_code, department) values ('Human Resources', 'HVP240', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'GIS051', 6);
insert into courses (course_name, course_code, department) values ('Training', 'AAR764', 3);
insert into courses (course_name, course_code, department) values ('Product Management', 'VXU881', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'BGZ595', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'EZW515', 6);
insert into courses (course_name, course_code, department) values ('Services', 'YHJ714', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'JXB317', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'HWP821', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'XQK926', 4);
insert into courses (course_name, course_code, department) values ('Support', 'IKM013', 3);
insert into courses (course_name, course_code, department) values ('Legal', 'WKQ556', 1);
insert into courses (course_name, course_code, department) values ('Support', 'IAX581', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'PGC644', 1);
insert into courses (course_name, course_code, department) values ('Support', 'WHE069', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'AZI489', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'TLB699', 5);
insert into courses (course_name, course_code, department) values ('Services', 'COS353', 4);
insert into courses (course_name, course_code, department) values ('Services', 'HEY875', 5);
insert into courses (course_name, course_code, department) values ('Sales', 'IFU996', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'JOZ909', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'VJN165', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'PQO443', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'GJG178', 7);
insert into courses (course_name, course_code, department) values ('Services', 'VLQ477', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'QGF652', 2);
insert into courses (course_name, course_code, department) values ('Training', 'LST939', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'PAF344', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'FZE566', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'OVR993', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'OCM121', 1);
insert into courses (course_name, course_code, department) values ('Services', 'UGT047', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'KHE937', 3);
insert into courses (course_name, course_code, department) values ('Legal', 'KCE440', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'MTF836', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'YOP494', 1);
insert into courses (course_name, course_code, department) values ('Engineering', 'UWF887', 6);
insert into courses (course_name, course_code, department) values ('Support', 'FAE548', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'VQI111', 2);
insert into courses (course_name, course_code, department) values ('Support', 'RQV487', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'OAR677', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'NEO717', 4);
insert into courses (course_name, course_code, department) values ('Support', 'MBR597', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'QWK391', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'BQA561', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'HAA357', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'MUK472', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'YEG084', 1);
insert into courses (course_name, course_code, department) values ('Services', 'GMX489', 4);
insert into courses (course_name, course_code, department) values ('Training', 'DVJ541', 5);
insert into courses (course_name, course_code, department) values ('Research and Development', 'LVO251', 5);
insert into courses (course_name, course_code, department) values ('Training', 'OGM303', 5);
insert into courses (course_name, course_code, department) values ('Training', 'CDE961', 6);
insert into courses (course_name, course_code, department) values ('Support', 'AXS527', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'BSS522', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'VAL622', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'LRB796', 6);
insert into courses (course_name, course_code, department) values ('Sales', 'OYG501', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'MZH165', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'XYL597', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'FUT013', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'TLJ627', 2);
insert into courses (course_name, course_code, department) values ('Accounting', 'YQF285', 5);
insert into courses (course_name, course_code, department) values ('Services', 'ARG591', 6);
insert into courses (course_name, course_code, department) values ('Training', 'NBR964', 1);
insert into courses (course_name, course_code, department) values ('Legal', 'NKE436', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'BNC512', 6);
insert into courses (course_name, course_code, department) values ('Business Development', 'ZBH780', 1);
insert into courses (course_name, course_code, department) values ('Engineering', 'HRH923', 5);
insert into courses (course_name, course_code, department) values ('Research and Development', 'CZB500', 7);
insert into courses (course_name, course_code, department) values ('Legal', 'VAN286', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'WIK245', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'AWU488', 3);
insert into courses (course_name, course_code, department) values ('Training', 'BYD695', 5);
insert into courses (course_name, course_code, department) values ('Training', 'NHT917', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'ZQX515', 3);
insert into courses (course_name, course_code, department) values ('Product Management', 'KGN304', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'EMN716', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'PMU091', 6);
insert into courses (course_name, course_code, department) values ('Services', 'QWF899', 1);
insert into courses (course_name, course_code, department) values ('Training', 'YNK279', 5);
insert into courses (course_name, course_code, department) values ('Support', 'LBP098', 5);
insert into courses (course_name, course_code, department) values ('Business Development', 'XPG071', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'EFF328', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'FOH974', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'MTN382', 3);
insert into courses (course_name, course_code, department) values ('Legal', 'ZYT312', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'ZPS594', 6);
insert into courses (course_name, course_code, department) values ('Services', 'EZE064', 1);
insert into courses (course_name, course_code, department) values ('Engineering', 'FAM109', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'DCN394', 2);
insert into courses (course_name, course_code, department) values ('Sales', 'AAC668', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'FJC099', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'AXP562', 3);
insert into courses (course_name, course_code, department) values ('Support', 'XVL309', 5);
insert into courses (course_name, course_code, department) values ('Business Development', 'XJA663', 2);
insert into courses (course_name, course_code, department) values ('Sales', 'KJK107', 2);
insert into courses (course_name, course_code, department) values ('Training', 'LEC831', 2);
insert into courses (course_name, course_code, department) values ('Services', 'IWI871', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'CVB407', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'RHF907', 1);
insert into courses (course_name, course_code, department) values ('Support', 'YFL016', 3);
insert into courses (course_name, course_code, department) values ('Research and Development', 'PZB043', 2);
insert into courses (course_name, course_code, department) values ('Training', 'SGJ448', 4);
insert into courses (course_name, course_code, department) values ('Engineering', 'ILG598', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'URF782', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'TIH012', 1);
insert into courses (course_name, course_code, department) values ('Training', 'GQO786', 3);
insert into courses (course_name, course_code, department) values ('Support', 'ASH945', 7);
insert into courses (course_name, course_code, department) values ('Services', 'EUB341', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'VAE865', 2);
insert into courses (course_name, course_code, department) values ('Support', 'BQV346', 7);
insert into courses (course_name, course_code, department) values ('Services', 'IGF138', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'DIX417', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'UGV519', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'LMQ903', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'STN807', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'QCC581', 2);
insert into courses (course_name, course_code, department) values ('Support', 'PDX568', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'HFT607', 5);
insert into courses (course_name, course_code, department) values ('Research and Development', 'FZA056', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'EHR153', 1);
insert into courses (course_name, course_code, department) values ('Support', 'KYS323', 5);
insert into courses (course_name, course_code, department) values ('Training', 'ZMN407', 1);
insert into courses (course_name, course_code, department) values ('Engineering', 'OVD906', 7);
insert into courses (course_name, course_code, department) values ('Engineering', 'MBK974', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'VHG264', 2);
insert into courses (course_name, course_code, department) values ('Training', 'LKW740', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'TNF781', 3);
insert into courses (course_name, course_code, department) values ('Human Resources', 'BPU957', 3);
insert into courses (course_name, course_code, department) values ('Support', 'TZL711', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'JUK767', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'MEL831', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'RXG742', 7);
insert into courses (course_name, course_code, department) values ('Legal', 'NDQ743', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'FOH067', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'XLH796', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'UZA567', 2);
insert into courses (course_name, course_code, department) values ('Training', 'OJY497', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'ZHO786', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'KLT739', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'PZR742', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'BLR411', 6);
insert into courses (course_name, course_code, department) values ('Training', 'LUQ856', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'OKJ890', 7);
insert into courses (course_name, course_code, department) values ('Training', 'ULP534', 6);
insert into courses (course_name, course_code, department) values ('Services', 'JDD853', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'MDV697', 5);
insert into courses (course_name, course_code, department) values ('Sales', 'NCI546', 2);
insert into courses (course_name, course_code, department) values ('Support', 'IWJ698', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'TLR887', 5);
insert into courses (course_name, course_code, department) values ('Services', 'PBD855', 6);
insert into courses (course_name, course_code, department) values ('Training', 'AZN217', 4);
insert into courses (course_name, course_code, department) values ('Training', 'ZUA524', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'BQM124', 1);
insert into courses (course_name, course_code, department) values ('Training', 'EXH843', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'KTA391', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'KZS065', 1);
insert into courses (course_name, course_code, department) values ('Support', 'KVE636', 5);
insert into courses (course_name, course_code, department) values ('Research and Development', 'ZND625', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'NPB532', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'VUW910', 2);
insert into courses (course_name, course_code, department) values ('Human Resources', 'OZZ948', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'BKV242', 3);
insert into courses (course_name, course_code, department) values ('Research and Development', 'PJO956', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'DTR138', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'GTB251', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'FBN693', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'URH645', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'LGJ797', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'BIK389', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'OHC197', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'HXF270', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'PCG735', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'CMJ853', 4);
insert into courses (course_name, course_code, department) values ('Training', 'IYZ845', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'HAH515', 7);
insert into courses (course_name, course_code, department) values ('Product Management', 'KUP155', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'NHZ815', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'KFZ770', 6);
insert into courses (course_name, course_code, department) values ('Sales', 'WDL512', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'RDE610', 5);
insert into courses (course_name, course_code, department) values ('Legal', 'VOP408', 1);
insert into courses (course_name, course_code, department) values ('Engineering', 'XBW264', 7);
insert into courses (course_name, course_code, department) values ('Support', 'GBG097', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'AFM390', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'GKR687', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'QQE199', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'OPB455', 7);
insert into courses (course_name, course_code, department) values ('Support', 'ZHP630', 1);
insert into courses (course_name, course_code, department) values ('Human Resources', 'PEH244', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'UGR586', 3);
insert into courses (course_name, course_code, department) values ('Services', 'QZF914', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'YVJ883', 3);
insert into courses (course_name, course_code, department) values ('Legal', 'KYU393', 5);
insert into courses (course_name, course_code, department) values ('Services', 'RLG304', 7);
insert into courses (course_name, course_code, department) values ('Accounting', 'WFO630', 6);
insert into courses (course_name, course_code, department) values ('Engineering', 'QAC488', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'JMQ351', 2);
insert into courses (course_name, course_code, department) values ('Services', 'PVM663', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'IHF264', 4);
insert into courses (course_name, course_code, department) values ('Support', 'LLN879', 1);
insert into courses (course_name, course_code, department) values ('Human Resources', 'TDL574', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'WBV209', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'GSP722', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'IOD478', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'MEV757', 6);
insert into courses (course_name, course_code, department) values ('Services', 'EVM253', 5);
insert into courses (course_name, course_code, department) values ('Legal', 'KFW214', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'DXB136', 2);
insert into courses (course_name, course_code, department) values ('Sales', 'OPR850', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'BFP141', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'MNF875', 6);
insert into courses (course_name, course_code, department) values ('Services', 'YON819', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'AQJ053', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'WFO871', 4);
insert into courses (course_name, course_code, department) values ('Training', 'PON030', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'VGD035', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'ZCY016', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'MDZ128', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'CCD245', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'FCR096', 5);
insert into courses (course_name, course_code, department) values ('Human Resources', 'XVX443', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'PSO103', 7);
insert into courses (course_name, course_code, department) values ('Accounting', 'XLV804', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'BFZ136', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'TOO718', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'LAB717', 7);
insert into courses (course_name, course_code, department) values ('Training', 'MJA675', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'JPV843', 3);
insert into courses (course_name, course_code, department) values ('Legal', 'YFM579', 7);
insert into courses (course_name, course_code, department) values ('Product Management', 'SNI018', 3);
insert into courses (course_name, course_code, department) values ('Training', 'GDA014', 3);
insert into courses (course_name, course_code, department) values ('Support', 'UMV189', 2);
insert into courses (course_name, course_code, department) values ('Business Development', 'UFN359', 1);
insert into courses (course_name, course_code, department) values ('Support', 'DSP167', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'LXA192', 6);
insert into courses (course_name, course_code, department) values ('Training', 'UQF955', 5);
insert into courses (course_name, course_code, department) values ('Services', 'BBX438', 1);
insert into courses (course_name, course_code, department) values ('Support', 'GKM008', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'UXU852', 5);
insert into courses (course_name, course_code, department) values ('Support', 'PHS364', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'UEM869', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'CKS743', 7);
insert into courses (course_name, course_code, department) values ('Support', 'RZC429', 5);
insert into courses (course_name, course_code, department) values ('Support', 'QEI314', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'OGB354', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'UWU063', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'SFD643', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'AUW582', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'KVE488', 5);
insert into courses (course_name, course_code, department) values ('Sales', 'VGG565', 3);
insert into courses (course_name, course_code, department) values ('Training', 'UFE590', 6);
insert into courses (course_name, course_code, department) values ('Business Development', 'VRL523', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'PKH464', 3);
insert into courses (course_name, course_code, department) values ('Training', 'YHN004', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'EEY437', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'EOH527', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'RCK584', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'VBR947', 1);
insert into courses (course_name, course_code, department) values ('Support', 'WFA809', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'MNP431', 1);
insert into courses (course_name, course_code, department) values ('Services', 'QBV499', 6);
insert into courses (course_name, course_code, department) values ('Support', 'GYB158', 5);
insert into courses (course_name, course_code, department) values ('Training', 'YTR321', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'NEB901', 1);
insert into courses (course_name, course_code, department) values ('Legal', 'QAW197', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'AIK701', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'DIK617', 1);
insert into courses (course_name, course_code, department) values ('Legal', 'WRP533', 5);
insert into courses (course_name, course_code, department) values ('Legal', 'MRN319', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'GHP799', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'YXI004', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'YXY599', 5);
insert into courses (course_name, course_code, department) values ('Services', 'KVY662', 3);
insert into courses (course_name, course_code, department) values ('Research and Development', 'FQQ208', 3);
insert into courses (course_name, course_code, department) values ('Training', 'SRB882', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'KPT605', 6);
insert into courses (course_name, course_code, department) values ('Training', 'SXT717', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'VZD721', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'QIL947', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'EDQ533', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'GGD592', 5);
insert into courses (course_name, course_code, department) values ('Support', 'GWT280', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'YCZ241', 2);
insert into courses (course_name, course_code, department) values ('Human Resources', 'BNB087', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'SLY402', 2);
insert into courses (course_name, course_code, department) values ('Training', 'LBG112', 7);
insert into courses (course_name, course_code, department) values ('Product Management', 'WFG204', 6);
insert into courses (course_name, course_code, department) values ('Sales', 'VPS465', 5);
insert into courses (course_name, course_code, department) values ('Legal', 'UTE305', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'CBG259', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'JAV935', 5);
insert into courses (course_name, course_code, department) values ('Marketing', 'VIV969', 5);
insert into courses (course_name, course_code, department) values ('Support', 'EGV714', 3);
insert into courses (course_name, course_code, department) values ('Human Resources', 'KPB689', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'ZLM027', 5);
insert into courses (course_name, course_code, department) values ('Business Development', 'SMZ663', 5);
insert into courses (course_name, course_code, department) values ('Research and Development', 'STF408', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'AYC310', 7);
insert into courses (course_name, course_code, department) values ('Support', 'XBE780', 1);
insert into courses (course_name, course_code, department) values ('Services', 'AKC893', 7);
insert into courses (course_name, course_code, department) values ('Engineering', 'XYO823', 4);
insert into courses (course_name, course_code, department) values ('Services', 'HDD130', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'ZUQ029', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'JLP296', 1);
insert into courses (course_name, course_code, department) values ('Support', 'MIS827', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'WNS215', 4);
insert into courses (course_name, course_code, department) values ('Engineering', 'BFT790', 1);
insert into courses (course_name, course_code, department) values ('Legal', 'NXB220', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'GKL805', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'FEX629', 4);
insert into courses (course_name, course_code, department) values ('Training', 'XBU953', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'HNA745', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'CIP230', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'QMA462', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'KBK504', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'NFH598', 6);
insert into courses (course_name, course_code, department) values ('Training', 'XZK843', 3);
insert into courses (course_name, course_code, department) values ('Services', 'YJG881', 3);
insert into courses (course_name, course_code, department) values ('Human Resources', 'VNN263', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'ERE510', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'HQM682', 5);
insert into courses (course_name, course_code, department) values ('Research and Development', 'ELA861', 5);
insert into courses (course_name, course_code, department) values ('Training', 'OWQ549', 2);
insert into courses (course_name, course_code, department) values ('Sales', 'ETB842', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'SOB352', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'QHC433', 1);
insert into courses (course_name, course_code, department) values ('Engineering', 'DVE837', 5);
insert into courses (course_name, course_code, department) values ('Legal', 'SHZ840', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'JQQ152', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'VZK802', 7);
insert into courses (course_name, course_code, department) values ('Training', 'GGZ197', 4);
insert into courses (course_name, course_code, department) values ('Support', 'PBF432', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'CWO184', 1);
insert into courses (course_name, course_code, department) values ('Support', 'ULH410', 6);
insert into courses (course_name, course_code, department) values ('Sales', 'TJE248', 2);
insert into courses (course_name, course_code, department) values ('Training', 'YJB820', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'IWU033', 4);
insert into courses (course_name, course_code, department) values ('Support', 'EYX922', 4);
insert into courses (course_name, course_code, department) values ('Training', 'ZFA226', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'KDK181', 7);
insert into courses (course_name, course_code, department) values ('Legal', 'ZLM189', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'NMP260', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'JLA848', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'POS504', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'ZAI786', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'DTF274', 2);
insert into courses (course_name, course_code, department) values ('Sales', 'JNU677', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'LUU169', 3);
insert into courses (course_name, course_code, department) values ('Training', 'MIM863', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'ZAE383', 7);
insert into courses (course_name, course_code, department) values ('Accounting', 'OHY457', 5);
insert into courses (course_name, course_code, department) values ('Services', 'IOD447', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'KET081', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'RUU510', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'DNF226', 5);
insert into courses (course_name, course_code, department) values ('Support', 'DUV307', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'LWT269', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'JGS955', 2);
insert into courses (course_name, course_code, department) values ('Accounting', 'AHW500', 3);
insert into courses (course_name, course_code, department) values ('Support', 'FDN813', 3);
insert into courses (course_name, course_code, department) values ('Product Management', 'CVQ777', 3);
insert into courses (course_name, course_code, department) values ('Support', 'FMN957', 7);
insert into courses (course_name, course_code, department) values ('Training', 'RBX059', 2);
insert into courses (course_name, course_code, department) values ('Human Resources', 'RZO335', 5);
insert into courses (course_name, course_code, department) values ('Training', 'YPW859', 6);
insert into courses (course_name, course_code, department) values ('Sales', 'IIW095', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'PDQ997', 6);
insert into courses (course_name, course_code, department) values ('Training', 'TGN083', 2);
insert into courses (course_name, course_code, department) values ('Engineering', 'GNV371', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'MAZ252', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'QYF288', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'TNO574', 6);
insert into courses (course_name, course_code, department) values ('Services', 'SLY939', 5);
insert into courses (course_name, course_code, department) values ('Training', 'UQI432', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'FJR638', 1);
insert into courses (course_name, course_code, department) values ('Legal', 'GKT771', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'VNS234', 1);
insert into courses (course_name, course_code, department) values ('Engineering', 'MGZ193', 6);
insert into courses (course_name, course_code, department) values ('Training', 'IIK490', 5);
insert into courses (course_name, course_code, department) values ('Support', 'XRS815', 2);
insert into courses (course_name, course_code, department) values ('Support', 'KUK582', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'XMZ340', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'GMQ999', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'HUF553', 5);
insert into courses (course_name, course_code, department) values ('Sales', 'IJL180', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'WAP771', 3);
insert into courses (course_name, course_code, department) values ('Training', 'EDX589', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'RYQ072', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'ESP736', 2);
insert into courses (course_name, course_code, department) values ('Support', 'FVR513', 6);
insert into courses (course_name, course_code, department) values ('Training', 'WSQ138', 2);
insert into courses (course_name, course_code, department) values ('Accounting', 'TUD216', 5);
insert into courses (course_name, course_code, department) values ('Training', 'DJY018', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'JTG220', 7);
insert into courses (course_name, course_code, department) values ('Training', 'UNT946', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'OIF732', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'FMY126', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'BFA901', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'GMU616', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'GQL733', 4);
insert into courses (course_name, course_code, department) values ('Services', 'KAX008', 1);
insert into courses (course_name, course_code, department) values ('Human Resources', 'RKK037', 7);
insert into courses (course_name, course_code, department) values ('Training', 'ATD736', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'HWS991', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'KHE998', 2);
insert into courses (course_name, course_code, department) values ('Services', 'MUH551', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'VXD663', 6);
insert into courses (course_name, course_code, department) values ('Training', 'XQG039', 5);
insert into courses (course_name, course_code, department) values ('Human Resources', 'NQS885', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'QLZ127', 3);
insert into courses (course_name, course_code, department) values ('Product Management', 'GON844', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'WXJ913', 2);
insert into courses (course_name, course_code, department) values ('Support', 'ZEK437', 5);
insert into courses (course_name, course_code, department) values ('Legal', 'MYO332', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'VPX289', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'WKK952', 3);
insert into courses (course_name, course_code, department) values ('Research and Development', 'JFO111', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'PYT105', 3);
insert into courses (course_name, course_code, department) values ('Training', 'DCT981', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'XSY748', 7);
insert into courses (course_name, course_code, department) values ('Accounting', 'HYW396', 6);
insert into courses (course_name, course_code, department) values ('Business Development', 'BGY350', 4);
insert into courses (course_name, course_code, department) values ('Support', 'TXT852', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'MND221', 2);
insert into courses (course_name, course_code, department) values ('Training', 'ZPE086', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'VXI317', 2);
insert into courses (course_name, course_code, department) values ('Engineering', 'DOR862', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'WMF213', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'KCF537', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'OCT589', 7);
insert into courses (course_name, course_code, department) values ('Accounting', 'TVX906', 1);
insert into courses (course_name, course_code, department) values ('Human Resources', 'EXK671', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'IMA111', 2);
insert into courses (course_name, course_code, department) values ('Support', 'IQQ599', 6);
insert into courses (course_name, course_code, department) values ('Services', 'WRL978', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'GTS349', 4);
insert into courses (course_name, course_code, department) values ('Engineering', 'KGJ414', 2);
insert into courses (course_name, course_code, department) values ('Sales', 'TZI651', 7);
insert into courses (course_name, course_code, department) values ('Accounting', 'GVK924', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'MCX559', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'GFU711', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'XWR774', 1);
insert into courses (course_name, course_code, department) values ('Support', 'XFT920', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'LOV393', 5);
insert into courses (course_name, course_code, department) values ('Marketing', 'ZOJ951', 2);
insert into courses (course_name, course_code, department) values ('Training', 'SFO039', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'QRX019', 1);
insert into courses (course_name, course_code, department) values ('Legal', 'NAT192', 6);
insert into courses (course_name, course_code, department) values ('Training', 'TAA221', 4);
insert into courses (course_name, course_code, department) values ('Engineering', 'SYW545', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'SEW784', 2);
insert into courses (course_name, course_code, department) values ('Human Resources', 'GNB253', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'ATY704', 2);
insert into courses (course_name, course_code, department) values ('Sales', 'GSU983', 3);
insert into courses (course_name, course_code, department) values ('Support', 'QCR967', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'NNJ255', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'NLZ474', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'SBV263', 6);
insert into courses (course_name, course_code, department) values ('Training', 'MFY555', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'NMC451', 7);
insert into courses (course_name, course_code, department) values ('Legal', 'QEV247', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'MZA778', 2);
insert into courses (course_name, course_code, department) values ('Business Development', 'HZY899', 4);
insert into courses (course_name, course_code, department) values ('Services', 'UFD229', 6);
insert into courses (course_name, course_code, department) values ('Engineering', 'BPE153', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'KUM383', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'XZO236', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'FSH127', 7);
insert into courses (course_name, course_code, department) values ('Training', 'GQS862', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'DFH244', 2);
insert into courses (course_name, course_code, department) values ('Support', 'GDD168', 3);
insert into courses (course_name, course_code, department) values ('Human Resources', 'VXK027', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'GYA641', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'NYW777', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'EEK559', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'MPS371', 2);
insert into courses (course_name, course_code, department) values ('Accounting', 'JOP740', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'VTN604', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'ZPX093', 7);
insert into courses (course_name, course_code, department) values ('Engineering', 'MSF388', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'BYW531', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'ZDT986', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'JMH817', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'QNY982', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'WKM538', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'GXS528', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'GEA735', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'ENC647', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'HSI400', 7);
insert into courses (course_name, course_code, department) values ('Support', 'JTK762', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'LCD399', 6);
insert into courses (course_name, course_code, department) values ('Support', 'ALL777', 4);
insert into courses (course_name, course_code, department) values ('Training', 'MEZ704', 7);
insert into courses (course_name, course_code, department) values ('Legal', 'JTU803', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'KSQ095', 1);
insert into courses (course_name, course_code, department) values ('Legal', 'SPQ933', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'GJK042', 1);
insert into courses (course_name, course_code, department) values ('Human Resources', 'MGO992', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'XEF087', 2);
insert into courses (course_name, course_code, department) values ('Services', 'GLA574', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'MYR498', 3);
insert into courses (course_name, course_code, department) values ('Support', 'SKL813', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'OOP599', 3);
insert into courses (course_name, course_code, department) values ('Human Resources', 'KYS199', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'PJV819', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'XKL072', 3);
insert into courses (course_name, course_code, department) values ('Support', 'THW056', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'FEV817', 2);
insert into courses (course_name, course_code, department) values ('Human Resources', 'LNR954', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'GEZ375', 4);
insert into courses (course_name, course_code, department) values ('Engineering', 'JFW378', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'QJG768', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'ZOP343', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'VHP111', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'ZQJ946', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'ZFB401', 5);
insert into courses (course_name, course_code, department) values ('Training', 'BMI759', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'UFH063', 1);
insert into courses (course_name, course_code, department) values ('Services', 'OZT865', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'INM782', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'JSJ599', 7);
insert into courses (course_name, course_code, department) values ('Product Management', 'TXI078', 6);
insert into courses (course_name, course_code, department) values ('Engineering', 'CIX840', 6);
insert into courses (course_name, course_code, department) values ('Engineering', 'AID807', 5);
insert into courses (course_name, course_code, department) values ('Business Development', 'DFS063', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'YCR602', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'SZK755', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'BTU548', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'PCN902', 7);
insert into courses (course_name, course_code, department) values ('Training', 'ZDE906', 7);
insert into courses (course_name, course_code, department) values ('Services', 'ZJZ626', 1);
insert into courses (course_name, course_code, department) values ('Training', 'THP328', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'XRX639', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'SGH358', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'ANU107', 3);
insert into courses (course_name, course_code, department) values ('Research and Development', 'HTF136', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'DCR696', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'IMH458', 7);
insert into courses (course_name, course_code, department) values ('Product Management', 'ATL134', 2);
insert into courses (course_name, course_code, department) values ('Services', 'BVC962', 5);
insert into courses (course_name, course_code, department) values ('Training', 'PCS227', 4);
insert into courses (course_name, course_code, department) values ('Services', 'GYI893', 2);
insert into courses (course_name, course_code, department) values ('Services', 'XRQ219', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'HSX145', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'DSZ505', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'JZF908', 2);
insert into courses (course_name, course_code, department) values ('Training', 'AZF703', 5);
insert into courses (course_name, course_code, department) values ('Human Resources', 'YMT688', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'AGG531', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'EDC685', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'IIU725', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'MXD775', 6);
insert into courses (course_name, course_code, department) values ('Services', 'BJL573', 7);
insert into courses (course_name, course_code, department) values ('Accounting', 'YJI915', 2);
insert into courses (course_name, course_code, department) values ('Human Resources', 'PBF564', 2);
insert into courses (course_name, course_code, department) values ('Business Development', 'ZMO373', 2);
insert into courses (course_name, course_code, department) values ('Engineering', 'PZM737', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'KEE527', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'HWF414', 1);
insert into courses (course_name, course_code, department) values ('Legal', 'HLP476', 1);
insert into courses (course_name, course_code, department) values ('Support', 'VDB019', 5);
insert into courses (course_name, course_code, department) values ('Human Resources', 'YNF992', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'GMW822', 7);
insert into courses (course_name, course_code, department) values ('Support', 'XGL337', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'WUL457', 7);
insert into courses (course_name, course_code, department) values ('Support', 'ARN064', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'MBE125', 7);
insert into courses (course_name, course_code, department) values ('Support', 'LIP081', 4);
insert into courses (course_name, course_code, department) values ('Services', 'KXS292', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'WEZ672', 1);
insert into courses (course_name, course_code, department) values ('Engineering', 'AWS697', 5);
insert into courses (course_name, course_code, department) values ('Services', 'VGI107', 2);
insert into courses (course_name, course_code, department) values ('Sales', 'CSD939', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'AQJ212', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'DCY893', 7);
insert into courses (course_name, course_code, department) values ('Engineering', 'SIT220', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'AEV362', 3);
insert into courses (course_name, course_code, department) values ('Human Resources', 'OYP828', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'WOX587', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'JMQ638', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'IRM559', 6);
insert into courses (course_name, course_code, department) values ('Training', 'HER240', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'ATJ069', 1);
insert into courses (course_name, course_code, department) values ('Support', 'KNY298', 4);
insert into courses (course_name, course_code, department) values ('Training', 'BOS395', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'DUU384', 1);
insert into courses (course_name, course_code, department) values ('Services', 'GGE469', 7);
insert into courses (course_name, course_code, department) values ('Accounting', 'QGN957', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'NKC775', 2);
insert into courses (course_name, course_code, department) values ('Services', 'DUC084', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'DGM017', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'EVM739', 5);
insert into courses (course_name, course_code, department) values ('Legal', 'FLM554', 3);
insert into courses (course_name, course_code, department) values ('Services', 'UDR373', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'VNX530', 1);
insert into courses (course_name, course_code, department) values ('Legal', 'HEX419', 7);
insert into courses (course_name, course_code, department) values ('Services', 'DAS739', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'CZI252', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'OVL092', 6);
insert into courses (course_name, course_code, department) values ('Engineering', 'DUZ313', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'WPY648', 6);
insert into courses (course_name, course_code, department) values ('Support', 'EDV480', 2);
insert into courses (course_name, course_code, department) values ('Training', 'LTB848', 2);
insert into courses (course_name, course_code, department) values ('Business Development', 'QRK212', 6);
insert into courses (course_name, course_code, department) values ('Business Development', 'QMO423', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'AXH569', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'BKU444', 5);
insert into courses (course_name, course_code, department) values ('Human Resources', 'PEC757', 1);
insert into courses (course_name, course_code, department) values ('Support', 'YRO230', 3);
insert into courses (course_name, course_code, department) values ('Training', 'JBS394', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'UMX966', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'TAZ908', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'YQY228', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'RPW571', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'QNN827', 2);
insert into courses (course_name, course_code, department) values ('Support', 'AST233', 6);
insert into courses (course_name, course_code, department) values ('Engineering', 'QCW015', 3);
insert into courses (course_name, course_code, department) values ('Services', 'NUP551', 7);
insert into courses (course_name, course_code, department) values ('Support', 'SZE908', 6);
insert into courses (course_name, course_code, department) values ('Support', 'FYV360', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'ZSR563', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'YYO629', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'DBZ127', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'ISH781', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'PMP354', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'JFD208', 4);
insert into courses (course_name, course_code, department) values ('Engineering', 'KFL916', 2);
insert into courses (course_name, course_code, department) values ('Engineering', 'FBG334', 6);
insert into courses (course_name, course_code, department) values ('Support', 'SBT898', 3);
insert into courses (course_name, course_code, department) values ('Support', 'HHI618', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'JBN919', 5);
insert into courses (course_name, course_code, department) values ('Marketing', 'RDX002', 5);
insert into courses (course_name, course_code, department) values ('Sales', 'EJJ741', 3);
insert into courses (course_name, course_code, department) values ('Support', 'HGQ573', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'THW543', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'HQA976', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'TNS316', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'YZU964', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'HKI359', 6);
insert into courses (course_name, course_code, department) values ('Sales', 'RDZ477', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'XED361', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'CYH061', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'DPI365', 7);
insert into courses (course_name, course_code, department) values ('Support', 'WBL532', 1);
insert into courses (course_name, course_code, department) values ('Services', 'VRN839', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'VJY837', 3);
insert into courses (course_name, course_code, department) values ('Human Resources', 'MIR269', 2);
insert into courses (course_name, course_code, department) values ('Support', 'BPP031', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'ZCQ662', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'INF614', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'XYY727', 5);
insert into courses (course_name, course_code, department) values ('Human Resources', 'ATP291', 3);
insert into courses (course_name, course_code, department) values ('Legal', 'OMU823', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'ERM617', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'GOS184', 5);
insert into courses (course_name, course_code, department) values ('Sales', 'YGL004', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'SPF518', 2);
insert into courses (course_name, course_code, department) values ('Human Resources', 'RYF088', 5);
insert into courses (course_name, course_code, department) values ('Research and Development', 'IYZ182', 2);
insert into courses (course_name, course_code, department) values ('Engineering', 'NWZ355', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'IGN359', 7);
insert into courses (course_name, course_code, department) values ('Support', 'KFH977', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'LXW250', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'FTU573', 2);
insert into courses (course_name, course_code, department) values ('Training', 'QND254', 3);
insert into courses (course_name, course_code, department) values ('Legal', 'CUX648', 2);
insert into courses (course_name, course_code, department) values ('Business Development', 'TPO517', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'XHX422', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'FCH782', 7);
insert into courses (course_name, course_code, department) values ('Engineering', 'THO031', 4);
insert into courses (course_name, course_code, department) values ('Engineering', 'VOI028', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'MUV504', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'GUC289', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'QQW924', 6);
insert into courses (course_name, course_code, department) values ('Support', 'AEY359', 2);
insert into courses (course_name, course_code, department) values ('Services', 'DAR564', 1);
insert into courses (course_name, course_code, department) values ('Training', 'JED686', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'HAV876', 5);
insert into courses (course_name, course_code, department) values ('Services', 'OJP472', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'ZRJ227', 3);
insert into courses (course_name, course_code, department) values ('Product Management', 'FIL609', 6);
insert into courses (course_name, course_code, department) values ('Sales', 'DYS601', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'HUM958', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'CYS088', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'ESO155', 1);
insert into courses (course_name, course_code, department) values ('Services', 'MGB182', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'ZXO345', 5);
insert into courses (course_name, course_code, department) values ('Business Development', 'GQK311', 1);
insert into courses (course_name, course_code, department) values ('Services', 'XPM850', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'BNT362', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'ILH548', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'QGN153', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'LBA937', 7);
insert into courses (course_name, course_code, department) values ('Engineering', 'SXF564', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'YZM960', 5);
insert into courses (course_name, course_code, department) values ('Sales', 'LKP022', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'VPA703', 3);
insert into courses (course_name, course_code, department) values ('Training', 'NOK013', 4);
insert into courses (course_name, course_code, department) values ('Business Development', 'KFC427', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'LWW714', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'OXE282', 5);
insert into courses (course_name, course_code, department) values ('Training', 'VWB029', 2);
insert into courses (course_name, course_code, department) values ('Business Development', 'LGO703', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'CGD106', 7);
insert into courses (course_name, course_code, department) values ('Engineering', 'ECW962', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'VHS785', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'GMV537', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'RMZ369', 6);
insert into courses (course_name, course_code, department) values ('Support', 'PID966', 4);
insert into courses (course_name, course_code, department) values ('Engineering', 'YGM917', 7);
insert into courses (course_name, course_code, department) values ('Legal', 'GVN853', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'BAQ686', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'XLQ601', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'KOJ369', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'HWP244', 2);
insert into courses (course_name, course_code, department) values ('Human Resources', 'EZP957', 2);
insert into courses (course_name, course_code, department) values ('Research and Development', 'SWQ255', 2);
insert into courses (course_name, course_code, department) values ('Engineering', 'RRQ024', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'XLF895', 7);
insert into courses (course_name, course_code, department) values ('Support', 'BQJ790', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'HSU874', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'PEG355', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'AUY090', 3);
insert into courses (course_name, course_code, department) values ('Training', 'MAF643', 6);
insert into courses (course_name, course_code, department) values ('Services', 'AQO482', 4);
insert into courses (course_name, course_code, department) values ('Services', 'XPA783', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'SDR861', 4);
insert into courses (course_name, course_code, department) values ('Training', 'VKF710', 3);
insert into courses (course_name, course_code, department) values ('Research and Development', 'VRF660', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'ESJ484', 6);
insert into courses (course_name, course_code, department) values ('Services', 'IZU419', 1);
insert into courses (course_name, course_code, department) values ('Services', 'USF804', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'WOP173', 5);
insert into courses (course_name, course_code, department) values ('Human Resources', 'TYY015', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'URR351', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'CEU242', 1);
insert into courses (course_name, course_code, department) values ('Training', 'OKH084', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'JWK444', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'ZDD211', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'PNI698', 4);
insert into courses (course_name, course_code, department) values ('Services', 'TYM569', 1);
insert into courses (course_name, course_code, department) values ('Support', 'FYI828', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'MMY441', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'CJS198', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'HFD593', 5);
insert into courses (course_name, course_code, department) values ('Support', 'ATR168', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'QFD728', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'PAW082', 2);
insert into courses (course_name, course_code, department) values ('Accounting', 'KWM077', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'YAQ505', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'PYT734', 1);
insert into courses (course_name, course_code, department) values ('Human Resources', 'EYC479', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'VGG847', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'LST066', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'HKM041', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'UXX405', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'KUY702', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'RZM319', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'YSQ261', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'HYK634', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'DVJ374', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'PEX148', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'OLP450', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'ELD796', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'ZZB756', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'ZFY164', 2);
insert into courses (course_name, course_code, department) values ('Services', 'GHU144', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'QPR962', 3);
insert into courses (course_name, course_code, department) values ('Support', 'EKG294', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'FGS600', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'VKI305', 3);
insert into courses (course_name, course_code, department) values ('Product Management', 'BJS317', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'UQL152', 6);
insert into courses (course_name, course_code, department) values ('Business Development', 'BOH581', 1);
insert into courses (course_name, course_code, department) values ('Services', 'YFE910', 4);
insert into courses (course_name, course_code, department) values ('Human Resources', 'MHI996', 4);
insert into courses (course_name, course_code, department) values ('Product Management', 'IDG407', 3);
insert into courses (course_name, course_code, department) values ('Services', 'RVH516', 2);
insert into courses (course_name, course_code, department) values ('Training', 'EXT354', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'GUE853', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'EGP583', 5);
insert into courses (course_name, course_code, department) values ('Human Resources', 'QNB418', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'WPB115', 6);
insert into courses (course_name, course_code, department) values ('Support', 'MGX337', 3);
insert into courses (course_name, course_code, department) values ('Engineering', 'XVF660', 7);
insert into courses (course_name, course_code, department) values ('Training', 'FLI975', 7);
insert into courses (course_name, course_code, department) values ('Services', 'XNJ117', 6);
insert into courses (course_name, course_code, department) values ('Business Development', 'YRF113', 1);
insert into courses (course_name, course_code, department) values ('Support', 'EVS681', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'HAQ739', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'PUT521', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'AMD937', 6);
insert into courses (course_name, course_code, department) values ('Human Resources', 'TPB739', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'NSF530', 4);
insert into courses (course_name, course_code, department) values ('Training', 'TXO848', 5);
insert into courses (course_name, course_code, department) values ('Business Development', 'AFF487', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'GYA988', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'UAW695', 7);
insert into courses (course_name, course_code, department) values ('Product Management', 'XZQ068', 5);
insert into courses (course_name, course_code, department) values ('Training', 'NPM195', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'QWM083', 7);
insert into courses (course_name, course_code, department) values ('Training', 'CBD189', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'QOF557', 7);
insert into courses (course_name, course_code, department) values ('Engineering', 'TDX261', 5);
insert into courses (course_name, course_code, department) values ('Legal', 'VZI529', 7);
insert into courses (course_name, course_code, department) values ('Services', 'DRK472', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'CIF492', 5);
insert into courses (course_name, course_code, department) values ('Sales', 'OAN904', 7);
insert into courses (course_name, course_code, department) values ('Engineering', 'IQS059', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'OKE993', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'SRA005', 4);
insert into courses (course_name, course_code, department) values ('Research and Development', 'MJH301', 5);
insert into courses (course_name, course_code, department) values ('Training', 'CWB945', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'STX085', 2);
insert into courses (course_name, course_code, department) values ('Training', 'PUX316', 6);
insert into courses (course_name, course_code, department) values ('Accounting', 'LBR515', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'CRJ505', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'IBS973', 6);
insert into courses (course_name, course_code, department) values ('Training', 'FQK967', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'ESG263', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'LYK746', 6);
insert into courses (course_name, course_code, department) values ('Engineering', 'CHA429', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'JFV616', 6);
insert into courses (course_name, course_code, department) values ('Support', 'GPY495', 2);
insert into courses (course_name, course_code, department) values ('Engineering', 'XDI136', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'VGO012', 5);
insert into courses (course_name, course_code, department) values ('Research and Development', 'PBS651', 5);
insert into courses (course_name, course_code, department) values ('Training', 'BHT491', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'KMY917', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'QZU639', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'RCA265', 7);
insert into courses (course_name, course_code, department) values ('Training', 'GYY288', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'GUD218', 7);
insert into courses (course_name, course_code, department) values ('Training', 'AWE272', 4);
insert into courses (course_name, course_code, department) values ('Support', 'JWM889', 5);
insert into courses (course_name, course_code, department) values ('Support', 'CAP223', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'DIF765', 5);
insert into courses (course_name, course_code, department) values ('Research and Development', 'GRO679', 3);
insert into courses (course_name, course_code, department) values ('Training', 'GBJ273', 3);
insert into courses (course_name, course_code, department) values ('Research and Development', 'WBT469', 2);
insert into courses (course_name, course_code, department) values ('Marketing', 'QOY456', 7);
insert into courses (course_name, course_code, department) values ('Product Management', 'KES250', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'TUH348', 4);
insert into courses (course_name, course_code, department) values ('Marketing', 'DLP009', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'OSB780', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'TGM307', 1);
insert into courses (course_name, course_code, department) values ('Engineering', 'BJE791', 5);
insert into courses (course_name, course_code, department) values ('Marketing', 'CTL444', 4);
insert into courses (course_name, course_code, department) values ('Sales', 'WYL445', 4);
insert into courses (course_name, course_code, department) values ('Training', 'OOW454', 2);
insert into courses (course_name, course_code, department) values ('Accounting', 'QHV989', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'QTZ706', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'HNF470', 5);
insert into courses (course_name, course_code, department) values ('Support', 'PLK822', 4);
insert into courses (course_name, course_code, department) values ('Engineering', 'RUB484', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'PUQ572', 1);
insert into courses (course_name, course_code, department) values ('Services', 'YMR674', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'FJQ144', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'UHR137', 7);
insert into courses (course_name, course_code, department) values ('Human Resources', 'XVA269', 7);
insert into courses (course_name, course_code, department) values ('Training', 'FLM951', 3);
insert into courses (course_name, course_code, department) values ('Sales', 'EYV701', 7);
insert into courses (course_name, course_code, department) values ('Support', 'UJH129', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'QJB158', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'TUH197', 1);
insert into courses (course_name, course_code, department) values ('Business Development', 'OZI845', 6);
insert into courses (course_name, course_code, department) values ('Research and Development', 'WJK898', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'RPT684', 3);
insert into courses (course_name, course_code, department) values ('Human Resources', 'FUK172', 1);
insert into courses (course_name, course_code, department) values ('Training', 'RLG339', 7);
insert into courses (course_name, course_code, department) values ('Services', 'UMD005', 6);
insert into courses (course_name, course_code, department) values ('Services', 'ZOU693', 1);
insert into courses (course_name, course_code, department) values ('Legal', 'OKP040', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'BQZ889', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'GCR445', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'IWW267', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'BLA826', 7);
insert into courses (course_name, course_code, department) values ('Business Development', 'CHP687', 4);
insert into courses (course_name, course_code, department) values ('Support', 'ZSL001', 1);
insert into courses (course_name, course_code, department) values ('Services', 'BQJ332', 1);
insert into courses (course_name, course_code, department) values ('Human Resources', 'LJM495', 1);
insert into courses (course_name, course_code, department) values ('Human Resources', 'JUD886', 2);
insert into courses (course_name, course_code, department) values ('Services', 'CPW585', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'XGN093', 3);
insert into courses (course_name, course_code, department) values ('Product Management', 'ABR669', 5);
insert into courses (course_name, course_code, department) values ('Training', 'SQA244', 5);
insert into courses (course_name, course_code, department) values ('Accounting', 'VGX964', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'MCG311', 3);
insert into courses (course_name, course_code, department) values ('Research and Development', 'QGL357', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'GTJ644', 7);
insert into courses (course_name, course_code, department) values ('Legal', 'UUM708', 3);
insert into courses (course_name, course_code, department) values ('Business Development', 'LEO267', 3);
insert into courses (course_name, course_code, department) values ('Accounting', 'IWC873', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'BKD147', 6);
insert into courses (course_name, course_code, department) values ('Marketing', 'OBO263', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'VKI084', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'OQV878', 2);
insert into courses (course_name, course_code, department) values ('Product Management', 'YOA672', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'PIG634', 7);
insert into courses (course_name, course_code, department) values ('Product Management', 'NRS181', 6);
insert into courses (course_name, course_code, department) values ('Product Management', 'WYP400', 2);
insert into courses (course_name, course_code, department) values ('Support', 'HNH115', 1);
insert into courses (course_name, course_code, department) values ('Training', 'HNI797', 7);
insert into courses (course_name, course_code, department) values ('Accounting', 'JMU860', 1);
insert into courses (course_name, course_code, department) values ('Accounting', 'HCG972', 4);
insert into courses (course_name, course_code, department) values ('Engineering', 'PXF922', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'ZXO459', 3);
insert into courses (course_name, course_code, department) values ('Legal', 'AHG213', 2);
insert into courses (course_name, course_code, department) values ('Human Resources', 'MGW257', 7);
insert into courses (course_name, course_code, department) values ('Sales', 'GFV012', 7);
insert into courses (course_name, course_code, department) values ('Legal', 'ZUM915', 6);
insert into courses (course_name, course_code, department) values ('Support', 'AGT539', 6);
insert into courses (course_name, course_code, department) values ('Sales', 'PDF561', 5);
insert into courses (course_name, course_code, department) values ('Sales', 'KKK531', 2);
insert into courses (course_name, course_code, department) values ('Legal', 'EYQ116', 5);
insert into courses (course_name, course_code, department) values ('Product Management', 'EPL660', 7);
insert into courses (course_name, course_code, department) values ('Training', 'ADQ051', 5);
insert into courses (course_name, course_code, department) values ('Services', 'POL009', 7);
insert into courses (course_name, course_code, department) values ('Legal', 'COK266', 4);
insert into courses (course_name, course_code, department) values ('Accounting', 'CYT480', 3);
insert into courses (course_name, course_code, department) values ('Marketing', 'LKE047', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'HWO079', 7);
insert into courses (course_name, course_code, department) values ('Research and Development', 'FLD127', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'PSG746', 7);
insert into courses (course_name, course_code, department) values ('Services', 'VOW192', 3);
insert into courses (course_name, course_code, department) values ('Research and Development', 'WFB143', 3);
insert into courses (course_name, course_code, department) values ('Product Management', 'DYW133', 6);
insert into courses (course_name, course_code, department) values ('Legal', 'FSB720', 2);
insert into courses (course_name, course_code, department) values ('Accounting', 'OJH869', 5);
insert into courses (course_name, course_code, department) values ('Human Resources', 'LGX688', 7);
insert into courses (course_name, course_code, department) values ('Marketing', 'JTX088', 1);
insert into courses (course_name, course_code, department) values ('Marketing', 'YXF138', 5);
insert into courses (course_name, course_code, department) values ('Training', 'EWH339', 1);
insert into courses (course_name, course_code, department) values ('Product Management', 'PNV182', 7);
insert into courses (course_name, course_code, department) values ('Services', 'PTB946', 1);
insert into courses (course_name, course_code, department) values ('Sales', 'HAT546', 7);
insert into courses (course_name, course_code, department) values ('Accounting', 'YVA482', 5);
insert into courses (course_name, course_code, department) values ('Engineering', 'XSE893', 7);
insert into courses (course_name, course_code, department) values ('Training', 'HAC236', 4);
insert into courses (course_name, course_code, department) values ('Legal', 'ZVN122', 2);
insert into courses (course_name, course_code, department) values ('Sales', 'RFX480', 1);
insert into courses (course_name, course_code, department) values ('Research and Development', 'XKA744', 4);
